# Generated by Django 4.2.2 on 2023-06-21 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('ID_Categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ID_Venta', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fecha', models.DateField()),
                ('ID_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.cliente')),
                ('ID_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
