# Generated by Django 4.2.2 on 2023-06-22 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ID_Cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ID_Producto',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
