# Generated by Django 4.2.2 on 2023-06-22 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='ID_Categoria',
            new_name='id_categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
